name: Build Dev

on: [push, workflow_dispatch]

jobs:
  linux-gmod-dedicated:
    runs-on: ubuntu-latest
    container: debian:bullseye
    name: "GMod Dedicated Server"

    steps:
    - name: Install Dependencies
      run: |
        dpkg --add-architecture i386
        apt update
        apt install -y build-essential git libstdc++6:i386 gcc-multilib g++-multilib zip curl

    - name: Checkout Mini Source SDK
      uses: actions/checkout@v4
      with:
        repository: RaphaelIT7/mini-source-sdk
        ref: gmod-changes

    - name: Checkout VPhysics Jolt
      uses: actions/checkout@v4
      with:
        path: gmod/src/vphysics_jolt
        submodules: recursive

    - name: Build GCC x86
      working-directory: gmod/src
      run: |
        chmod +x createjoltprojects_server.sh
        chmod +x devtools/bin/vpc_linux
        chmod +x devtools/bin/vpc
        chmod +x devtools/gendbg.sh
        ./createjoltprojects_server.sh 
        make -f jolt.mak -j $(nproc)

    - name: Create zip file
      run: |
        cd gmod/game
        zip -r vphysics_jolt_gmod_dedicated_linux32.zip bin
        mv vphysics_jolt_gmod_dedicated_linux32.zip ../../

    - name: Deploy to pterodactyl
      run: |
        curl "https://${{secrets.PTERODACTYL_URL}}/api/client/servers/${{secrets.PTERODACTYL_SERVER}}/files/write?file=%2Fvphysics_jolt_gmod_dedicated_linux32.zip" \
              -H 'Accept: application/json' \
              -H 'Authorization: Bearer ${{secrets.PTERODACTYL_KEY}}' \
              -X POST \
              --data-binary '@vphysics_jolt_gmod_dedicated_linux32.zip'

        curl "https://${{secrets.PTERODACTYL_URL}}/api/client/servers/${{secrets.PTERODACTYL_SERVER}}/files/decompress" \
              -H 'Accept: application/json' \
              -H 'Content-Type: application/json' \
              -H 'Authorization: Bearer ${{secrets.PTERODACTYL_KEY}}' \
              -X POST \
              -d '{"root": "/", "file": "vphysics_jolt_gmod_dedicated_linux32.zip"}' 